public with sharing class ProductItemDTO {
  @AuraEnabled
  public String productItemId;
  @AuraEnabled
  public String productId;
  @AuraEnabled
  public String productName;
  @AuraEnabled
  public String productItemNumber;
  @AuraEnabled
  public Decimal productItemQuantity;
  @AuraEnabled
  public String productItemSerialNumber;
  @AuraEnabled
  public String productItemUrl;
  @AuraEnabled
  public String productUrl;
}
